contact/urls.py
from django.urls import path

from .views import contact_form_view
from .utils.decorators import check_recaptcha


app_name = 'contact'
urlpatterns = [
    path('', check_recaptcha(contact_form_view), name='contact_form'),
]

contact/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import format_lazy


class EmailMessage(models.Model):
    name = models.CharField(_('Sender Name'), max_length=40)
    from_email = models.EmailField(_('Sender E-mail'), max_length=255)
    phone = models.CharField(_('Sender Phone Number'), max_length=15, null=True, blank=True)
    subject = models.CharField(_('Message Subject'), max_length=255, null=True, blank=True)
    message = models.TextField(_('Message Text'))
    sent = models.DateTimeField(_('Sent'), auto_now_add=True)

    class Meta:
        verbose_name = _('E-mail Message')
        verbose_name_plural = _('E-mail Messages')

    def __str__(self):
        return str(format_lazy(_('Message from {name}'), name=self.name))

contact/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _
from django.utils.text import format_lazy
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from django.conf import settings

from .models import EmailMessage


class ContactForm(forms.ModelForm):
    name = forms.CharField(required=True, min_length=2, max_length=40, label=_('Name'),
                           widget=forms.TextInput(attrs={'placeholder': _('What\'s your name?'),
                                                         'class': 'form-group textinput textInput form-control'}, ),
                           error_messages={'required': _('Name field is required.')},)
    phone = forms.CharField(required=False, min_length=7, max_length=15, label=_('Phone Number'),
                            widget=forms.TextInput(attrs={'placeholder': '12223334455',
                                                          'class': 'form-group textinput textInput form-control'}))

    class Meta:
        model = EmailMessage
        exclude = ['sent',]
        widgets = {
            'from_email': forms.EmailInput(attrs={'placeholder': 'user@domain.com',
                                                  'class': 'form-group textinput textInput emailinput form-control',}),
            'subject': forms.TextInput(attrs={'placeholder': _('Message subject'),
                                        'class': 'form-group textinput textInput form-control',}),
            'message': forms.Textarea(attrs={'placeholder': _('Your message'),
                                       'class': 'form-group textinput textInput form-control',}),

        }
        labels = {
            'from_email': _('Your E-mail'),
            'subject': _('Subject'),
            'message': _('Message'),
        }
        error_messages = {
            'message': {
                'required': _('Message field is required.'),
            }
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        pattern = r'^[a-zA-Zа-яА-ЯёЁ]+( +[a-zA-Zа-яА-ЯёЁ]+)*$'
        if not re.match(pattern, name):
            self.add_error('name', _('A name must contain only letters and spaces.'))
        return name

    def clean_from_email(self):
        from_email = self.cleaned_data['from_email']
        return from_email.lower()

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        pattern = r'^\d+$'
        if not re.match(pattern, phone) and phone != '':
            self.add_error('phone', _('A phone number must contain only digits.'))
        return phone

    def send_email(self):
        name = self.cleaned_data['name']
        from_email = self.cleaned_data['from_email']
        phone = self.cleaned_data['phone']
        subject = self.cleaned_data['subject']
        message = format_lazy(_('{message}\n'
                                'From: {name} {from_email} {phone}'), message=self.cleaned_data['message'], name=name,
                              from_email=from_email, phone=phone)

        recipient_list = [manager[1] for manager in settings.MANAGERS]

        try:
            send_mail(subject, message, from_email, recipient_list, fail_silently=False)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

contact/views.py
from django.views.generic.edit import FormView
from django.utils.translation import gettext_lazy as _
from django.utils.text import format_lazy
from django.urls import reverse_lazy
from django.http import JsonResponse

from .forms import ContactForm


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'contact/contact_form.html'
    success_url = reverse_lazy('contact:contact_form')
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if request.recaptcha_is_valid and form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        response = super().form_valid(form)

        form.send_email()

        form.save()

        name = form.cleaned_data['name']

        if self.request.is_ajax():
            data = {
                'success_msg': format_lazy(_('Thank you, {name}! I\'ll reply you soon...'), name=name)
            }
            return JsonResponse(data)
        else:
            return response

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            if self.request.recaptcha_is_valid:
              return JsonResponse(form.errors, status=400)
            else:
                return JsonResponse({
                    'detail': _('Please confirm that you are not a robot.')}, status=400)
        else:
            response.status_code = 400
            return response


contact_form_view = ContactFormView.as_view()

contact/templates/contact/contact_form.html
{% load i18n %}

<div class="row">
  <div class="col-md-6 offset-md-3 mb-5">
    <form id="contactForm">{% csrf_token %}
      {% for field in form %}
        <div id="div_{{ field.id_for_label }}" class="form-group">
          <label for="{{ field.id_for_label }}" {% if field.field.required %}class="requiredField{% if field.widget.attrs.readonly %} readOnlyLabel{% endif %}{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}</label>
          <div class>
            {{ field }}
            {% if field.errors %}
              <ul class="errorlist">
              {% for error in field.errors %}
                <li id="error_{{ forloop.counter0 }}_{{ field.id_for_label }}" class="text-danger">
                  <strong>{{ error|escape }}</strong>
                </li>
              {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>
      {% endfor %}

      <script src="https://www.google.com/recaptcha/api.js"></script>
      <div class="form-group g-recaptcha" data-sitekey={{ sitekey }}></div>

      <div id="success"></div>
      <button id="#sendMessageButton" class="primaryAction btn btn-primary" type="submit">{% trans "Send" %} &raquo;</button>
    </form>
  </div>
</div>

<script type="text/javascript">
  function csrfSafeMethod(method) {
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }

  var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

  $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
      }
  });

  $("#contactForm").submit(function (event) {
      event.preventDefault();
      var name = $("input#id_name").val();
      var from_email = $("input#id_from_email").val();
      var phone = $("input#id_phone").val();
      var subject = $("input#id_subject").val();
      var message = $("textarea#id_message").val();
      var recaptcha = grecaptcha.getResponse();
      $this = $("#sendMessageButton");
      $this.prop("disabled", true);
      $.ajax({
        url: "/contact/",
        type: "POST",
        data: {
            name: name,
            phone: phone,
            from_email: from_email,
            subject: subject,
            message: message,
            recaptcha: recaptcha,
        },
        cache: false,
        success: function (response) {
            $("#success").html("<div class='alert alert-success'>");
            $("#success > .alert-success")
                .html(
                    "<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;"
                )
                .append("</button>");
            $("#success > .alert-success").append(
                "<strong>" + response.success_msg + "</strong>"
            );
            $("#success > .alert-success").append("</div>");
            $("#contactForm").trigger("reset");
            grecaptcha.reset()
        },
        error: function (response) {
            var error_msg = '';
            $.each(response.responseJSON, function (key, value) {
                error_msg += value + "<br />";
            });
            $("#success").html("<div class='alert alert-danger'>");
            $("#success > .alert-danger")
                .html(
                    "<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;"
                )
                .append("</button>");
            $("#success > .alert-danger").append(
                $("<strong>").html(
                    error_msg,
                ),
            );
            $("#success > .alert-danger").append("</div>");
            grecaptcha.reset()
        },
        complete: function () {
            setTimeout(function () {
                $this.prop("disabled", false);
            }, 1000);
        }
      });
  });
</script>